name: IdentityServer Admin Build And Deploy

on:
  push:
    paths-ignore:
      - 'Project4/src/Project4.STS.Identity/**'
      - 'Project4/src/Project4.Admin.Api/**'
      - '.github/workflows/**'
    branches: [ main ]

    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 'Project4/src/Project4.Admin/Project4.Admin.csproj' -c Release --no-restore
    
    - name: Publish
      run: dotnet publish 'Project4/src/Project4.Admin/Project4.Admin.csproj' -c Release -o app/build


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
         name: identityserver-admin-drop
         path: app/build


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    
    - name: Remove all files
      run: rm -rfv /var/www/ids-admin.latinonet.online/*
    
    - name: Download a Build Artifact IdentityServer Admin 
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: identityserver-admin-drop
        # Destination path
        path: /var/www/ids-admin.latinonet.online


    - uses: microsoft/variable-substitution@v1 
      with:
          files: '/var/www/ids-admin.latinonet.online/appsettings.json'
      env:
          ConnectionStrings.ConfigurationDbConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings.PersistedGrantDbConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings.IdentityDbConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings.AdminLogDbConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings.AdminAuditLogDbConnection: ${{ secrets.CONNECTION_STRING }}
          ConnectionStrings.DataProtectionDbConnection: ${{ secrets.CONNECTION_STRING }}
          AdminConfiguration.ClientSecret: ${{ secrets.ADMINCONFIGURATION__CLIENTSECRET }}

             
        
    - name: Restart the app
      run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart ids-admin.latinonet.online.service
